config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy], module: :posts
      resources :likes, only: [:new, :create], module: :posts
    end
  end
  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all # Admins can manage all resources
    else
      can :read, :all
      can %i[create destroy], [Post, Comment], user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post, foreign_key: 'post_id'

  validates :text, presence: true

  after_save :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_post_likes_counter

  private

  # The function `update_post_likes_counter` increments the `likes_counter`
  # attribute of a post.
  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, dependent: :destroy

  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    # user.update(post_counter: user.posts.count)
    post_count = user.posts.count
    user.update(posts_counter: post_count.zero? ? 0 : post_count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', counter_cache: true
  has_many :comments
  has_many :likes

  # Validation

  validates :name, presence: true # This is validating that the `Name`
  # attribute of the `User` model is present, meaning it cannot be blank or nil.
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # is adding a validation to the `User` model. It ensures that the `PostCounter` attribute is a
  # numerical value and that it is greater than or equal to 0. This means that the `PostCounter`
  # attribute cannot be a non-integer value or a negative number.
  # The function below retrieves the three most recent posts written
  # by the author.
  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def index
    @comments = Comment.all
    render json: @comments
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(text: params[:text], user_id: params[:user_id])

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def index
    @posts = Post.all
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :post
  load_and_authorize_resource :comment, through: :post
  # This method is used to instantiate a new comment
  def new
    @comment = Comment.new
  end

  # This method is used to create a new comment on behalf of the current_user
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user: current_user))
    if @comment.save
      cookies[:comment_id] = @comment.id
      redirect_to user_post_path(@post.user, @post), notice: 'Comment added successfully.'
    else
      render :new
    end
  end

  # This method is used to delete a comment on behalf of the current_user
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@post.user, @post), notice: 'Comment deleted successfully.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # This method is used to instantiate a new like
  def new
    @like = Like.new
  end

  # This method is used to create a new like on behalf of the current_user
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.build(like_params.merge(post_id: @post.id))
    if @like.save
      @like.update_post_likes_counter
      redirect_to user_post_path(@post.user, @post), notice: 'Post liked successfully.'
    else
      render :new
    end
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  # The index method is used to display all the posts for a given user.
  # The index method will be called when a user navigates to the URL /users/:user_id/posts.
  def index
    # current_user = User.find(params[:user_id])
    @user = current_user
    @posts = current_user.posts.includes(:comments)
    @posts = Post.all
  end

  # The show method is used to retrieve a specific post from the database and display it to the user.
  def show
    @user = current_user
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
    @like = Like.new
    cookies[:post_id] = @post.id if @post.present?

    return unless @post.nil?

    redirect_to root_path, alert: 'Comment deleted successfully.'
  end

  # The create method is used to create a new post on behalf of the current_user.
  def create
    @post = current_user.posts.build(post_params) # Creates a new post and associates it with the current user

    if @post.save # If the post is successfully saved
      @post.increment_posts_counter
      redirect_to user_posts_path(current_user), notice: 'Successfully created post.' # Redirects to the user's posts
    else
      @posts = current_user.posts
      render :index # Renders the index page with the user's posts if there are errors
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @post.update_posts_counter
    redirect_to user_posts_path(current_user), notice: 'Post deleted successfully.'
  end

  private

  # The function `post_params` is used to extract and permit specific parameters from
  # the `params` object in a Ruby on Rails application.
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    cookies[:user_id] = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="posts-container">
  <div class="posts-header">
    <img src="<%= current_user.photo %>" alt="user photo">
    <div>
      <h2>Name: <%= current_user.name %></h2>
      <h4>Number of posts: <%= current_user.posts_counter %></h4>
    </div>
  </div>
  
  <% @posts.each do |post| %>
    <div class="all-posts-container">
      <div class="all-posts">
        <h2><%= post.title %></h2>
        <p><%= post.text %></p>
        <div>
          <span>Comments: <%= post.comments_counter %></span>
          <span>Likes: <%= post.likes_counter %></span>
          <%# <h5>
            <%= link_to "Read post", user_post_path(@user, post) %>
            <%# <% if can?(:destroy, post) %>
              <%# <%= link_to "Delete", user_post_path(@user, post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %> %>
            <%# <% end %> 
            <%# </h5>  %>
        </div>
      </div>
    </div>
    
    <div class="recent-comments-container">
      <h3>Recent Comments</h3>
      <% post.five_most_recent_comments.each do |comment| %>
        <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
      <% end %>
    </div>
    
  <% end %>
</div>

<%= form_with(model: @post, url: user_posts_path(current_user), method: :post) do |form| %>
  <h2>Create a new post</h2>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :text %>
  <%= form.text_area :text %><br>

  <%= form.submit "Create Post" %><br>
<% end %>
<button type="button">Pagination</button>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>
  <div class="single-post">
    <h2><%= @post.title %></h2>
    <div>
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text %></p>
    <div>
  <%= form_with(url: user_post_likes_path(@post.user, @post), method: :post) do |form| %>
  <%= form.submit "Like" %>
<% end %>
    </div>
  </div>
  <div class="post-comments">

<%= form_with(model: @comment, url: user_post_comments_path(@post.user, @post), method: :post) do |form| %>
  <%= form.submit "Add Comment" %>
 <h2>Add a comment</h2>
  <%= form.label :text %>
  <%= form.text_area :text %><br>

  <%= form.submit "Add Comment" %><br>
<% end %>
  </div>
    
  <h1 class="comments-header">All comments</h1>
  <div class="post-comments">
  <% @post.comments.each do |comment| %>
      <h4>Username: <%= comment.user.name %> - <span> <%= comment.text %> </span>
      <% if can?(:destroy, comment) %>
          <%= button_to "Delete", delete_comment_path(users_id: @post.user.id, posts_id: @post.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
        <% end %> </h4>
  <% end %>
  </div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">/</div>

app/views/shared/_header.html.erb
<div h1 class="header">  
<h1>Blog App</h1>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
</div>

app/views/users/index.html.erb
<%= render "shared/header" %>
<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<% @users.each do |user| %>
    <div class="user-container">
      <img src="<%= user.photo %>" alt="user photo">
      <div>
        <h2>Name: <%= user.name %></h2>
        <h4>Number of posts: <%= user.posts_counter %></h4>
        <h4> 
          <%= link_to "View profile", user_path(user) %>
        </h4>
        </div>
    </div>
<% end %>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="show-user-container">
  <div class="show-header">
    <img src="<%= @user.photo %>" alt="user photo">
    <div>
      <h2>Name: <%= @user.name %></h2>
      <h4>Number of posts: <%= @user.posts_counter %></h4>
    </div>
  </div>
</div>
<div class="bio">
  <h2>Bio</h2>
  <p><%= @user.bio %></p>
</div>

<% @user.three_most_recent_posts.each do |post| %>
  <div class="show-posts">
    <h2><%= link_to post.title, user_post_path(@user, post) %></h2>
    <p><%= post.text %></p>
    <div>
      <span>Comments: <%= post.comments_counter %></span>
      <span>Likes: <%= post.likes_counter %></span>
    </div>
  </div>
<% end %>

<button type="button">
  <%= link_to "See all posts", user_posts_path(@user.id) %>
</button>

<%= render "shared/footer" %>